services:
  - type: web
    name: algolens
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: AI_API_TOKEN
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: AI_API_URL
        value: https://api.groq.com/openai/v1/chat/completions
      - key: AI_MODEL
        value: llama-3.3-70b-versatile
